version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: yourpdf-prod-redis
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME:-unknowndockerishere}/yourpdf-backend:latest
    container_name: yourpdf-prod-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - tmp_data:/app/tmp
      - static_data:/app/static
    environment:
      - REDIS_URL=redis://redis:6379/0
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - redis
    restart: always

  celery_worker:
    image: ${DOCKERHUB_USERNAME:-unknowndockerishere}/yourpdf-backend:latest
    container_name: yourpdf-prod-celery-worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - tmp_data:/app/tmp
      - static_data:/app/static
    environment:
      - REDIS_URL=redis://redis:6379/0
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - redis
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME:-unknowndockerishere}/yourpdf-frontend:latest
    container_name: yourpdf-prod-frontend
    restart: always

  nginx:
    image: ${DOCKERHUB_USERNAME:-unknowndockerishere}/yourpdf-nginx:latest
    container_name: yourpdf-prod-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  tmp_data:
  static_data:
